server:
  port: 8080
  servlet:
     context-path: /identity

spring:
  name: "identity-service"

  datasource:
    url: jdbc:mysql://localhost:3307/identity_service?useSSL=false&serverTimezone=UTC
    username: root
    password: 100504
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

jwt:
  signerKey: "d+cNWwyPpTw3HwhOJWXtJ8ZbiVUTFdwfGdVXigHmMbafFr83Gm43VFBnMZIH0OU0"



